-- MySQL Script generated by MySQL Workbench
-- Tue Feb 13 16:10:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema machine_metrics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `machine_metrics` ;

-- -----------------------------------------------------
-- Schema machine_metrics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `machine_metrics` DEFAULT CHARACTER SET utf8 ;
USE `machine_metrics` ;

-- -----------------------------------------------------
-- Table `machine_metrics`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machine_metrics`.`person` (
  `full_name` VARCHAR(45) NOT NULL,
  `supervisor_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`full_name`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `full_name_UNIQUE` ON `machine_metrics`.`person` (`full_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `machine_metrics`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machine_metrics`.`project` (
  `idproject` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(150) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `status_project` ENUM('CREATED', 'PENDING', 'ACTIVE', 'COMPLETE') NOT NULL,
  `person_full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproject`, `person_full_name`),
  CONSTRAINT `fk_project_person1`
    FOREIGN KEY (`person_full_name`)
    REFERENCES `machine_metrics`.`person` (`full_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idproject_UNIQUE` ON `machine_metrics`.`project` (`idproject` ASC) VISIBLE;

CREATE INDEX `fk_project_person1_idx` ON `machine_metrics`.`project` (`person_full_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `machine_metrics`.`person_has_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machine_metrics`.`person_has_project` (
  `person_full_name` VARCHAR(45) NOT NULL,
  `project_idproject` INT NOT NULL,
  PRIMARY KEY (`person_full_name`, `project_idproject`),
  CONSTRAINT `fk_person_has_project_person`
    FOREIGN KEY (`person_full_name`)
    REFERENCES `machine_metrics`.`person` (`full_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_project_project1`
    FOREIGN KEY (`project_idproject`)
    REFERENCES `machine_metrics`.`project` (`idproject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_person_has_project_project1_idx` ON `machine_metrics`.`person_has_project` (`project_idproject` ASC) VISIBLE;

CREATE INDEX `fk_person_has_project_person_idx` ON `machine_metrics`.`person_has_project` (`person_full_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `machine_metrics`.`performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `machine_metrics`.`performance` (
  `idperformance` INT NOT NULL AUTO_INCREMENT,
  `kpi_type` VARCHAR(45) NOT NULL,
  `project_idproject` INT NOT NULL,
  `project_person_full_name` VARCHAR(45) NOT NULL,
  `kpi_num` FLOAT NULL,
  `kpi_str` VARCHAR(45) NULL,
  `kpi_str_porcent` FLOAT NULL,
  `kpi_descripcion` LONGTEXT NOT NULL,
  `date_upload` DATE NOT NULL,
  PRIMARY KEY (`idperformance`, `project_idproject`, `project_person_full_name`),
  CONSTRAINT `fk_performance_project1`
    FOREIGN KEY (`project_idproject` , `project_person_full_name`)
    REFERENCES `machine_metrics`.`project` (`idproject` , `person_full_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_performance_project1_idx` ON `machine_metrics`.`performance` (`project_idproject` ASC, `project_person_full_name` ASC) VISIBLE;

CREATE UNIQUE INDEX `idperformance_UNIQUE` ON `machine_metrics`.`performance` (`idperformance` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
